### ISSUE TITLE
Please, move to the Calculix organization

### ISSUE THREAD

**Issue by imirzov** [timmaxw/os2cx#1]
Dear Tim,

I'm trying to develop [CalculiX organization](https://github.com/calculix) on the GitHub to unite all developers and tools in one place. So, please, could you move there your project?

All your permissions will be kept, so do not afraid. Old URL will be kept also, new URL will be github.com/calculix/os2cx.

In your project Settings go to Options -> Danger Zone -> Transfer ownership. Click on ‘Transfer’ button, then type ‘calculix’ as user.

Thank you in advance!

**Comment by timmaxw** [comment]
Hi @imirzov. Thanks for setting up the CalculiX organization. It's great to see that other people are also working on CalculiX-related tools. However, I'd prefer to keep the os2cx repository attached to my own GitHub account.
