### ISSUE TITLE
No ability to use console binary to calculate maximum deflection from shell scripts

### ISSUE THREAD

**Issue by waynepiekarski** [timmaxw/os2cx#4]
Thanks for developing this awesome code to integrate OpenSCAD with Calculix. I was trying to replicate an old experiment by J. D. Stachiw with acrylic viewports, and wanted to perform calculations over a range of thicknesses and diameters, then capture all this into a CSV file for graphing and then compare with the actual real world measurements. https://github.com/waynepiekarski/openscad2calculix4stachiw

However, it seems like only the GUI is able to calculate and display the maximum deflection or any other values, but this requires the user to manually read the value. For automating in scripts, it needs to be in the console binary as well.

It seems like console support for printing out the deflection is not available. I copy and pasted a few things from the GUI code to make it work and have included a github commit below that contains this if anyone is interested in using it. But this might be something to add in a future version:
https://github.com/waynepiekarski/openscad2calculix4stachiw/commit/f29058586725721a553196ca57b8d126d2eafee6

**Comment by timmaxw** [comment]
Hi @waynepiekarski! Glad you were able to put os2cx to good use. Sorry for the long delay in replying; I had accidentally disabled notifications for this repository for some reason.

Good idea for printing out measurements in the console. As you can probably tell, I never really used the console binary myself. I've implemented this feature on the master branch.
