### ISSUE TITLE
installation instructions insufficient

### ISSUE THREAD

**Issue by nmz787** [timmaxw/os2cx#5]

**Comment by timmaxw** [comment]
Currently the only way to install OS2CX is to compile it from source. Sorry!

You'd have to do something like:
1. Download the source code
2. Install the dependencies listed in the README
3. Install either Qt Creator (graphical IDE) or QMake (command-line tool)
4. Compile the project using Qt Creator or QMake

I've been meaning to make an AppImage but I haven't found the time... :(

**Comment by nmz787** [comment]
Sorry I was editing the first post and my laptop died. I meant to say the qt package isn't listed, and there's like a hundred in `apt`. I got as far as installing qmake, but that's insufficient

**Comment by timmaxw** [comment]
Ah, I see. Does `sudo apt-get install qtbase5-dev` work?

**Comment by timmaxw** [comment]
I set up a prebuilt AppImage you can download: https://github.com/timmaxw/os2cx/releases/tag/latest

**Comment by nmz787** [comment]
> sudo apt-get install qtbase5-dev

that gets rid of the error message (`Could not find qmake spec 'linux-g++'.`) and now I see a `Makefile`!

Previously I installed this package `qt5-qmake-bin`... not sure now if the qtbase5-dev comes with `qmake`, but I'll assume not at this point.

**Comment by nmz787** [comment]
tests now pass! thanks!
